[keybindings.Global]
"<q>" = "Quit"         # Quit the application
"<ctrl-d>" = "Quit"    # Another way to quit
"<ctrl-c>" = "Quit"    # Yet another way to quit
"<ctrl-z>" = "Suspend" # Suspend the application
[keybindings.Navigation]
"<j>" = "GoDown"                    # Move the cursor down
"<k>" = "GoUp"                      # Move the cursor up
"<h>" = "FocusOnWorkspaces"         # Focus on workspaces
"<l>" = "FocusOnTasks"              # Focus on tasks
"<shift-g>" = "GoToTop"             # Move the cursor to the top
"<g><g>" = "GoToBottom"             # Move the cursor to the bottom
"<i>" = "AddItemBefore"             # Add an item before the current one
"<a>" = "AddItemAfter"              # Add an item after the current one
"<d>" = "DeleteItem"                # Delete the current item
"<e>" = "EditItem"                  # Edit the current item
"<shift-j>" = "MoveItemDown"        # Move the current item down
"<shift-k>" = "MoveItemUp"          # Move the current item up
"<ctrl-shift-k>" = "MoveItemTop"    # Move the current item to the top
"<ctrl-shift-j>" = "MoveItemBottom" # Move the current item to the bottom
"<x>" = "ToggleCompletion"          # Toggle a task as completed or not
"<shift-e>" = "EditDescription"     # Edit the description of the current item
"<=>" = "IncreasePriority"          # Increase the priority of the current item
"<+>" = "IncreasePriority"          # Increase the priority of the current item
"<->" = "DecreasePriority"          # Decrease the priority of the current item
"<_>" = "DecreasePriority"          # Decrease the priority of the current item
"s" = "OpenSortMenu"                # Open the sort menu
"<Esc>" = "Cancel"                  # Cancel the current operation
"<Enter>" = "Select"                # Submit the current operation
"<!>" = "ToggleSortDirection"       # Toggle the sort direction
[styles]
"Highlight" = "color14"
"Selected" = "bold on color10"
"Normal" = ""
"Error" = "red"
"Completed" = "green"
"Priority1" = "bold red"
"Priority2" = "bold yellow"
"Priority3" = ""
"Priority4" = "color8"
